version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/exercises/1-course-introduction/1-introduction/2-embedded"
      - "/exercises/5-rust-for-web/1-rust-for-web-servers/1-lettuce-crop"
      - "/exercises/5-rust-for-web/2-rust-in-the-cloud/2-lettuce-crop-scaleway"
      - "/exercises/5-rust-for-web/3-rust-in-the-browser/1-lettuce-crop-wasm"
      - "/exercises/7-rust-for-data-science/2-async-rust-python/1-hello-world"
      - "/exercises/7-rust-for-data-science/2-async-rust-python/2-strompy"
      - "/exercises/8-embedded/1-embedded-ecosystem/1-lsm303agr-id"
      - "/exercises/8-embedded/2-portable-drivers/1-lsm303agr-driver"
      - "/exercises/8-embedded/3-async-on-embedded/1-compass"
      - "/exercises/8-embedded/4-embassy-framework/1-embassy-project"
    schedule:
      interval: "monthly"
    groups:
      frequent-updaters:
        patterns:
          - "serde*"
          - "anyhow"
  - package-ecosystem: "npm"
    directory: "/slides/"
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      ci-dependencies:
        patterns:
          - "*"
