[package]
name = "lettuce-crop"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
image = "0.25.5"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.6.2", features = ["fs"] }
